version: '2'

services:
  builder:
    image: "erlang:24"
    network_mode: host
    volumes:
      - "./:/source"
    working_dir: "/source"
    environment: # Required for tests because / is not writable
      ERL_FLAGS: -nocookie
      REBAR_CACHE_DIR: /tmp
    command: [sh, "-c", "exit"]

  erlang-discovery:
    image: "nginx:1.17"
    volumes:
      - "./nginx-config/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - node0
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - node7
      - node8
      - node9

  node0:
    image: "erlang:24" # prod release has the ERTS, so a smaller image is ok, but this one is already pulled for the builder
    volumes:
      - "./:/source"
    working_dir: "/source"
    command: [_build/prod/last_release_launcher, foreground]
  node1:
    extends: node0
  node2:
    extends: node0
  node3:
    extends: node0
  node4:
    extends: node0
  node5:
    extends: node0
  node6:
    extends: node0
  node7:
    extends: node0
  node8:
    extends: node0
  node9:
    extends: node0

